/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleTransportationRouteImport } from './routes/vehicle-transportation'
import { Route as VehicleMarketplaceRouteImport } from './routes/vehicle-marketplace'
import { Route as VehicleFinancingRouteImport } from './routes/vehicle-financing'
import { Route as VehicleConsignmentRouteImport } from './routes/vehicle-consignment'
import { Route as UsedCarsForSaleRouteImport } from './routes/used-cars-for-sale'
import { Route as UpcomingAutoAuctionsRouteImport } from './routes/upcoming-auto-auctions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellYourVehicleRouteImport } from './routes/sell-your-vehicle'
import { Route as RepoCarAuctionsRouteImport } from './routes/repo-car-auctions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GovernmentVehicleAuctionsRouteImport } from './routes/government-vehicle-auctions'
import { Route as FleetVehiclesRouteImport } from './routes/fleet-vehicles'
import { Route as DealerInventoryRouteImport } from './routes/dealer-inventory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarsForSaleRouteImport } from './routes/cars-for-sale'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutoAuctionsRouteImport } from './routes/auto-auctions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseVansRouteImport } from './routes/browse.vans'
import { Route as BrowseSuvsRouteImport } from './routes/browse.suvs'
import { Route as BrowseSedansRouteImport } from './routes/browse.sedans'
import { Route as BrowsePickupTrucksRouteImport } from './routes/browse.pickup-trucks'
import { Route as BrowseLuxuryCarsRouteImport } from './routes/browse.luxury-cars'
import { Route as BrowseHybridVehiclesRouteImport } from './routes/browse.hybrid-vehicles'
import { Route as BrowseElectricVehiclesRouteImport } from './routes/browse.electric-vehicles'
import { Route as BrowseCommercialVehiclesRouteImport } from './routes/browse.commercial-vehicles'
import { Route as BlogTransportationGuidesRouteImport } from './routes/blog.transportation-guides'
import { Route as BlogSellingGuidesRouteImport } from './routes/blog.selling-guides'
import { Route as BlogMarketInsightsRouteImport } from './routes/blog.market-insights'
import { Route as BlogFinancingGuidesRouteImport } from './routes/blog.financing-guides'
import { Route as BlogBuyingGuidesRouteImport } from './routes/blog.buying-guides'
import { Route as BlogAutoAuctionGuidesRouteImport } from './routes/blog.auto-auction-guides'

const VehicleTransportationRoute = VehicleTransportationRouteImport.update({
  id: '/vehicle-transportation',
  path: '/vehicle-transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleMarketplaceRoute = VehicleMarketplaceRouteImport.update({
  id: '/vehicle-marketplace',
  path: '/vehicle-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleFinancingRoute = VehicleFinancingRouteImport.update({
  id: '/vehicle-financing',
  path: '/vehicle-financing',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleConsignmentRoute = VehicleConsignmentRouteImport.update({
  id: '/vehicle-consignment',
  path: '/vehicle-consignment',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedCarsForSaleRoute = UsedCarsForSaleRouteImport.update({
  id: '/used-cars-for-sale',
  path: '/used-cars-for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingAutoAuctionsRoute = UpcomingAutoAuctionsRouteImport.update({
  id: '/upcoming-auto-auctions',
  path: '/upcoming-auto-auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourVehicleRoute = SellYourVehicleRouteImport.update({
  id: '/sell-your-vehicle',
  path: '/sell-your-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoCarAuctionsRoute = RepoCarAuctionsRouteImport.update({
  id: '/repo-car-auctions',
  path: '/repo-car-auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentVehicleAuctionsRoute =
  GovernmentVehicleAuctionsRouteImport.update({
    id: '/government-vehicle-auctions',
    path: '/government-vehicle-auctions',
    getParentRoute: () => rootRouteImport,
  } as any)
const FleetVehiclesRoute = FleetVehiclesRouteImport.update({
  id: '/fleet-vehicles',
  path: '/fleet-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerInventoryRoute = DealerInventoryRouteImport.update({
  id: '/dealer-inventory',
  path: '/dealer-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsForSaleRoute = CarsForSaleRouteImport.update({
  id: '/cars-for-sale',
  path: '/cars-for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoAuctionsRoute = AutoAuctionsRouteImport.update({
  id: '/auto-auctions',
  path: '/auto-auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseVansRoute = BrowseVansRouteImport.update({
  id: '/browse/vans',
  path: '/browse/vans',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSuvsRoute = BrowseSuvsRouteImport.update({
  id: '/browse/suvs',
  path: '/browse/suvs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSedansRoute = BrowseSedansRouteImport.update({
  id: '/browse/sedans',
  path: '/browse/sedans',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePickupTrucksRoute = BrowsePickupTrucksRouteImport.update({
  id: '/browse/pickup-trucks',
  path: '/browse/pickup-trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseLuxuryCarsRoute = BrowseLuxuryCarsRouteImport.update({
  id: '/browse/luxury-cars',
  path: '/browse/luxury-cars',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHybridVehiclesRoute = BrowseHybridVehiclesRouteImport.update({
  id: '/browse/hybrid-vehicles',
  path: '/browse/hybrid-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseElectricVehiclesRoute = BrowseElectricVehiclesRouteImport.update({
  id: '/browse/electric-vehicles',
  path: '/browse/electric-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCommercialVehiclesRoute =
  BrowseCommercialVehiclesRouteImport.update({
    id: '/browse/commercial-vehicles',
    path: '/browse/commercial-vehicles',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTransportationGuidesRoute =
  BlogTransportationGuidesRouteImport.update({
    id: '/transportation-guides',
    path: '/transportation-guides',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogSellingGuidesRoute = BlogSellingGuidesRouteImport.update({
  id: '/selling-guides',
  path: '/selling-guides',
  getParentRoute: () => BlogRoute,
} as any)
const BlogMarketInsightsRoute = BlogMarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => BlogRoute,
} as any)
const BlogFinancingGuidesRoute = BlogFinancingGuidesRouteImport.update({
  id: '/financing-guides',
  path: '/financing-guides',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBuyingGuidesRoute = BlogBuyingGuidesRouteImport.update({
  id: '/buying-guides',
  path: '/buying-guides',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAutoAuctionGuidesRoute = BlogAutoAuctionGuidesRouteImport.update({
  id: '/auto-auction-guides',
  path: '/auto-auction-guides',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-auctions': typeof AutoAuctionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cars-for-sale': typeof CarsForSaleRoute
  '/contact': typeof ContactRoute
  '/dealer-inventory': typeof DealerInventoryRoute
  '/fleet-vehicles': typeof FleetVehiclesRoute
  '/government-vehicle-auctions': typeof GovernmentVehicleAuctionsRoute
  '/privacy': typeof PrivacyRoute
  '/repo-car-auctions': typeof RepoCarAuctionsRoute
  '/sell-your-vehicle': typeof SellYourVehicleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-auto-auctions': typeof UpcomingAutoAuctionsRoute
  '/used-cars-for-sale': typeof UsedCarsForSaleRoute
  '/vehicle-consignment': typeof VehicleConsignmentRoute
  '/vehicle-financing': typeof VehicleFinancingRoute
  '/vehicle-marketplace': typeof VehicleMarketplaceRoute
  '/vehicle-transportation': typeof VehicleTransportationRoute
  '/blog/auto-auction-guides': typeof BlogAutoAuctionGuidesRoute
  '/blog/buying-guides': typeof BlogBuyingGuidesRoute
  '/blog/financing-guides': typeof BlogFinancingGuidesRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/blog/selling-guides': typeof BlogSellingGuidesRoute
  '/blog/transportation-guides': typeof BlogTransportationGuidesRoute
  '/browse/commercial-vehicles': typeof BrowseCommercialVehiclesRoute
  '/browse/electric-vehicles': typeof BrowseElectricVehiclesRoute
  '/browse/hybrid-vehicles': typeof BrowseHybridVehiclesRoute
  '/browse/luxury-cars': typeof BrowseLuxuryCarsRoute
  '/browse/pickup-trucks': typeof BrowsePickupTrucksRoute
  '/browse/sedans': typeof BrowseSedansRoute
  '/browse/suvs': typeof BrowseSuvsRoute
  '/browse/vans': typeof BrowseVansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-auctions': typeof AutoAuctionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cars-for-sale': typeof CarsForSaleRoute
  '/contact': typeof ContactRoute
  '/dealer-inventory': typeof DealerInventoryRoute
  '/fleet-vehicles': typeof FleetVehiclesRoute
  '/government-vehicle-auctions': typeof GovernmentVehicleAuctionsRoute
  '/privacy': typeof PrivacyRoute
  '/repo-car-auctions': typeof RepoCarAuctionsRoute
  '/sell-your-vehicle': typeof SellYourVehicleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-auto-auctions': typeof UpcomingAutoAuctionsRoute
  '/used-cars-for-sale': typeof UsedCarsForSaleRoute
  '/vehicle-consignment': typeof VehicleConsignmentRoute
  '/vehicle-financing': typeof VehicleFinancingRoute
  '/vehicle-marketplace': typeof VehicleMarketplaceRoute
  '/vehicle-transportation': typeof VehicleTransportationRoute
  '/blog/auto-auction-guides': typeof BlogAutoAuctionGuidesRoute
  '/blog/buying-guides': typeof BlogBuyingGuidesRoute
  '/blog/financing-guides': typeof BlogFinancingGuidesRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/blog/selling-guides': typeof BlogSellingGuidesRoute
  '/blog/transportation-guides': typeof BlogTransportationGuidesRoute
  '/browse/commercial-vehicles': typeof BrowseCommercialVehiclesRoute
  '/browse/electric-vehicles': typeof BrowseElectricVehiclesRoute
  '/browse/hybrid-vehicles': typeof BrowseHybridVehiclesRoute
  '/browse/luxury-cars': typeof BrowseLuxuryCarsRoute
  '/browse/pickup-trucks': typeof BrowsePickupTrucksRoute
  '/browse/sedans': typeof BrowseSedansRoute
  '/browse/suvs': typeof BrowseSuvsRoute
  '/browse/vans': typeof BrowseVansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-auctions': typeof AutoAuctionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cars-for-sale': typeof CarsForSaleRoute
  '/contact': typeof ContactRoute
  '/dealer-inventory': typeof DealerInventoryRoute
  '/fleet-vehicles': typeof FleetVehiclesRoute
  '/government-vehicle-auctions': typeof GovernmentVehicleAuctionsRoute
  '/privacy': typeof PrivacyRoute
  '/repo-car-auctions': typeof RepoCarAuctionsRoute
  '/sell-your-vehicle': typeof SellYourVehicleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-auto-auctions': typeof UpcomingAutoAuctionsRoute
  '/used-cars-for-sale': typeof UsedCarsForSaleRoute
  '/vehicle-consignment': typeof VehicleConsignmentRoute
  '/vehicle-financing': typeof VehicleFinancingRoute
  '/vehicle-marketplace': typeof VehicleMarketplaceRoute
  '/vehicle-transportation': typeof VehicleTransportationRoute
  '/blog/auto-auction-guides': typeof BlogAutoAuctionGuidesRoute
  '/blog/buying-guides': typeof BlogBuyingGuidesRoute
  '/blog/financing-guides': typeof BlogFinancingGuidesRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/blog/selling-guides': typeof BlogSellingGuidesRoute
  '/blog/transportation-guides': typeof BlogTransportationGuidesRoute
  '/browse/commercial-vehicles': typeof BrowseCommercialVehiclesRoute
  '/browse/electric-vehicles': typeof BrowseElectricVehiclesRoute
  '/browse/hybrid-vehicles': typeof BrowseHybridVehiclesRoute
  '/browse/luxury-cars': typeof BrowseLuxuryCarsRoute
  '/browse/pickup-trucks': typeof BrowsePickupTrucksRoute
  '/browse/sedans': typeof BrowseSedansRoute
  '/browse/suvs': typeof BrowseSuvsRoute
  '/browse/vans': typeof BrowseVansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-auctions'
    | '/blog'
    | '/cars-for-sale'
    | '/contact'
    | '/dealer-inventory'
    | '/fleet-vehicles'
    | '/government-vehicle-auctions'
    | '/privacy'
    | '/repo-car-auctions'
    | '/sell-your-vehicle'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-auto-auctions'
    | '/used-cars-for-sale'
    | '/vehicle-consignment'
    | '/vehicle-financing'
    | '/vehicle-marketplace'
    | '/vehicle-transportation'
    | '/blog/auto-auction-guides'
    | '/blog/buying-guides'
    | '/blog/financing-guides'
    | '/blog/market-insights'
    | '/blog/selling-guides'
    | '/blog/transportation-guides'
    | '/browse/commercial-vehicles'
    | '/browse/electric-vehicles'
    | '/browse/hybrid-vehicles'
    | '/browse/luxury-cars'
    | '/browse/pickup-trucks'
    | '/browse/sedans'
    | '/browse/suvs'
    | '/browse/vans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-auctions'
    | '/blog'
    | '/cars-for-sale'
    | '/contact'
    | '/dealer-inventory'
    | '/fleet-vehicles'
    | '/government-vehicle-auctions'
    | '/privacy'
    | '/repo-car-auctions'
    | '/sell-your-vehicle'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-auto-auctions'
    | '/used-cars-for-sale'
    | '/vehicle-consignment'
    | '/vehicle-financing'
    | '/vehicle-marketplace'
    | '/vehicle-transportation'
    | '/blog/auto-auction-guides'
    | '/blog/buying-guides'
    | '/blog/financing-guides'
    | '/blog/market-insights'
    | '/blog/selling-guides'
    | '/blog/transportation-guides'
    | '/browse/commercial-vehicles'
    | '/browse/electric-vehicles'
    | '/browse/hybrid-vehicles'
    | '/browse/luxury-cars'
    | '/browse/pickup-trucks'
    | '/browse/sedans'
    | '/browse/suvs'
    | '/browse/vans'
  id:
    | '__root__'
    | '/'
    | '/auto-auctions'
    | '/blog'
    | '/cars-for-sale'
    | '/contact'
    | '/dealer-inventory'
    | '/fleet-vehicles'
    | '/government-vehicle-auctions'
    | '/privacy'
    | '/repo-car-auctions'
    | '/sell-your-vehicle'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-auto-auctions'
    | '/used-cars-for-sale'
    | '/vehicle-consignment'
    | '/vehicle-financing'
    | '/vehicle-marketplace'
    | '/vehicle-transportation'
    | '/blog/auto-auction-guides'
    | '/blog/buying-guides'
    | '/blog/financing-guides'
    | '/blog/market-insights'
    | '/blog/selling-guides'
    | '/blog/transportation-guides'
    | '/browse/commercial-vehicles'
    | '/browse/electric-vehicles'
    | '/browse/hybrid-vehicles'
    | '/browse/luxury-cars'
    | '/browse/pickup-trucks'
    | '/browse/sedans'
    | '/browse/suvs'
    | '/browse/vans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoAuctionsRoute: typeof AutoAuctionsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CarsForSaleRoute: typeof CarsForSaleRoute
  ContactRoute: typeof ContactRoute
  DealerInventoryRoute: typeof DealerInventoryRoute
  FleetVehiclesRoute: typeof FleetVehiclesRoute
  GovernmentVehicleAuctionsRoute: typeof GovernmentVehicleAuctionsRoute
  PrivacyRoute: typeof PrivacyRoute
  RepoCarAuctionsRoute: typeof RepoCarAuctionsRoute
  SellYourVehicleRoute: typeof SellYourVehicleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UpcomingAutoAuctionsRoute: typeof UpcomingAutoAuctionsRoute
  UsedCarsForSaleRoute: typeof UsedCarsForSaleRoute
  VehicleConsignmentRoute: typeof VehicleConsignmentRoute
  VehicleFinancingRoute: typeof VehicleFinancingRoute
  VehicleMarketplaceRoute: typeof VehicleMarketplaceRoute
  VehicleTransportationRoute: typeof VehicleTransportationRoute
  BrowseCommercialVehiclesRoute: typeof BrowseCommercialVehiclesRoute
  BrowseElectricVehiclesRoute: typeof BrowseElectricVehiclesRoute
  BrowseHybridVehiclesRoute: typeof BrowseHybridVehiclesRoute
  BrowseLuxuryCarsRoute: typeof BrowseLuxuryCarsRoute
  BrowsePickupTrucksRoute: typeof BrowsePickupTrucksRoute
  BrowseSedansRoute: typeof BrowseSedansRoute
  BrowseSuvsRoute: typeof BrowseSuvsRoute
  BrowseVansRoute: typeof BrowseVansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-transportation': {
      id: '/vehicle-transportation'
      path: '/vehicle-transportation'
      fullPath: '/vehicle-transportation'
      preLoaderRoute: typeof VehicleTransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-marketplace': {
      id: '/vehicle-marketplace'
      path: '/vehicle-marketplace'
      fullPath: '/vehicle-marketplace'
      preLoaderRoute: typeof VehicleMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-financing': {
      id: '/vehicle-financing'
      path: '/vehicle-financing'
      fullPath: '/vehicle-financing'
      preLoaderRoute: typeof VehicleFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-consignment': {
      id: '/vehicle-consignment'
      path: '/vehicle-consignment'
      fullPath: '/vehicle-consignment'
      preLoaderRoute: typeof VehicleConsignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used-cars-for-sale': {
      id: '/used-cars-for-sale'
      path: '/used-cars-for-sale'
      fullPath: '/used-cars-for-sale'
      preLoaderRoute: typeof UsedCarsForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-auto-auctions': {
      id: '/upcoming-auto-auctions'
      path: '/upcoming-auto-auctions'
      fullPath: '/upcoming-auto-auctions'
      preLoaderRoute: typeof UpcomingAutoAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-vehicle': {
      id: '/sell-your-vehicle'
      path: '/sell-your-vehicle'
      fullPath: '/sell-your-vehicle'
      preLoaderRoute: typeof SellYourVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-car-auctions': {
      id: '/repo-car-auctions'
      path: '/repo-car-auctions'
      fullPath: '/repo-car-auctions'
      preLoaderRoute: typeof RepoCarAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-vehicle-auctions': {
      id: '/government-vehicle-auctions'
      path: '/government-vehicle-auctions'
      fullPath: '/government-vehicle-auctions'
      preLoaderRoute: typeof GovernmentVehicleAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-vehicles': {
      id: '/fleet-vehicles'
      path: '/fleet-vehicles'
      fullPath: '/fleet-vehicles'
      preLoaderRoute: typeof FleetVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-inventory': {
      id: '/dealer-inventory'
      path: '/dealer-inventory'
      fullPath: '/dealer-inventory'
      preLoaderRoute: typeof DealerInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-for-sale': {
      id: '/cars-for-sale'
      path: '/cars-for-sale'
      fullPath: '/cars-for-sale'
      preLoaderRoute: typeof CarsForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-auctions': {
      id: '/auto-auctions'
      path: '/auto-auctions'
      fullPath: '/auto-auctions'
      preLoaderRoute: typeof AutoAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/vans': {
      id: '/browse/vans'
      path: '/browse/vans'
      fullPath: '/browse/vans'
      preLoaderRoute: typeof BrowseVansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/suvs': {
      id: '/browse/suvs'
      path: '/browse/suvs'
      fullPath: '/browse/suvs'
      preLoaderRoute: typeof BrowseSuvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/sedans': {
      id: '/browse/sedans'
      path: '/browse/sedans'
      fullPath: '/browse/sedans'
      preLoaderRoute: typeof BrowseSedansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/pickup-trucks': {
      id: '/browse/pickup-trucks'
      path: '/browse/pickup-trucks'
      fullPath: '/browse/pickup-trucks'
      preLoaderRoute: typeof BrowsePickupTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/luxury-cars': {
      id: '/browse/luxury-cars'
      path: '/browse/luxury-cars'
      fullPath: '/browse/luxury-cars'
      preLoaderRoute: typeof BrowseLuxuryCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/hybrid-vehicles': {
      id: '/browse/hybrid-vehicles'
      path: '/browse/hybrid-vehicles'
      fullPath: '/browse/hybrid-vehicles'
      preLoaderRoute: typeof BrowseHybridVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/electric-vehicles': {
      id: '/browse/electric-vehicles'
      path: '/browse/electric-vehicles'
      fullPath: '/browse/electric-vehicles'
      preLoaderRoute: typeof BrowseElectricVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/commercial-vehicles': {
      id: '/browse/commercial-vehicles'
      path: '/browse/commercial-vehicles'
      fullPath: '/browse/commercial-vehicles'
      preLoaderRoute: typeof BrowseCommercialVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/transportation-guides': {
      id: '/blog/transportation-guides'
      path: '/transportation-guides'
      fullPath: '/blog/transportation-guides'
      preLoaderRoute: typeof BlogTransportationGuidesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/selling-guides': {
      id: '/blog/selling-guides'
      path: '/selling-guides'
      fullPath: '/blog/selling-guides'
      preLoaderRoute: typeof BlogSellingGuidesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/market-insights': {
      id: '/blog/market-insights'
      path: '/market-insights'
      fullPath: '/blog/market-insights'
      preLoaderRoute: typeof BlogMarketInsightsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/financing-guides': {
      id: '/blog/financing-guides'
      path: '/financing-guides'
      fullPath: '/blog/financing-guides'
      preLoaderRoute: typeof BlogFinancingGuidesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/buying-guides': {
      id: '/blog/buying-guides'
      path: '/buying-guides'
      fullPath: '/blog/buying-guides'
      preLoaderRoute: typeof BlogBuyingGuidesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/auto-auction-guides': {
      id: '/blog/auto-auction-guides'
      path: '/auto-auction-guides'
      fullPath: '/blog/auto-auction-guides'
      preLoaderRoute: typeof BlogAutoAuctionGuidesRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogAutoAuctionGuidesRoute: typeof BlogAutoAuctionGuidesRoute
  BlogBuyingGuidesRoute: typeof BlogBuyingGuidesRoute
  BlogFinancingGuidesRoute: typeof BlogFinancingGuidesRoute
  BlogMarketInsightsRoute: typeof BlogMarketInsightsRoute
  BlogSellingGuidesRoute: typeof BlogSellingGuidesRoute
  BlogTransportationGuidesRoute: typeof BlogTransportationGuidesRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogAutoAuctionGuidesRoute: BlogAutoAuctionGuidesRoute,
  BlogBuyingGuidesRoute: BlogBuyingGuidesRoute,
  BlogFinancingGuidesRoute: BlogFinancingGuidesRoute,
  BlogMarketInsightsRoute: BlogMarketInsightsRoute,
  BlogSellingGuidesRoute: BlogSellingGuidesRoute,
  BlogTransportationGuidesRoute: BlogTransportationGuidesRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoAuctionsRoute: AutoAuctionsRoute,
  BlogRoute: BlogRouteWithChildren,
  CarsForSaleRoute: CarsForSaleRoute,
  ContactRoute: ContactRoute,
  DealerInventoryRoute: DealerInventoryRoute,
  FleetVehiclesRoute: FleetVehiclesRoute,
  GovernmentVehicleAuctionsRoute: GovernmentVehicleAuctionsRoute,
  PrivacyRoute: PrivacyRoute,
  RepoCarAuctionsRoute: RepoCarAuctionsRoute,
  SellYourVehicleRoute: SellYourVehicleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UpcomingAutoAuctionsRoute: UpcomingAutoAuctionsRoute,
  UsedCarsForSaleRoute: UsedCarsForSaleRoute,
  VehicleConsignmentRoute: VehicleConsignmentRoute,
  VehicleFinancingRoute: VehicleFinancingRoute,
  VehicleMarketplaceRoute: VehicleMarketplaceRoute,
  VehicleTransportationRoute: VehicleTransportationRoute,
  BrowseCommercialVehiclesRoute: BrowseCommercialVehiclesRoute,
  BrowseElectricVehiclesRoute: BrowseElectricVehiclesRoute,
  BrowseHybridVehiclesRoute: BrowseHybridVehiclesRoute,
  BrowseLuxuryCarsRoute: BrowseLuxuryCarsRoute,
  BrowsePickupTrucksRoute: BrowsePickupTrucksRoute,
  BrowseSedansRoute: BrowseSedansRoute,
  BrowseSuvsRoute: BrowseSuvsRoute,
  BrowseVansRoute: BrowseVansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
